<?php

########################################################################
# Extension Manager/Repository config file for ext: "nxshowroom"
#
# Auto generated by Extension Builder 2012-03-26
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Showroom',
	'description' => 'Showcase your Extensions, TypoScript and ViewHelpers. Organize Your Projects and find the things you\'ve done.',
	'category' => 'plugin',
	'author' => 'Noel Bossart, Beat Gebistorf',
	'author_email' => 'noel.bossart@me.com, beat.gebistorf@namics.com',
	'author_company' => 'Namics AG, Namics AG',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3.0',
			'fluid' => '1.3.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>